// Shared portfolio data — placeholder content the user will replace later.
const PORTFOLIO = {
  name: "your_name",
  handle: "you@portfolio",
  domain: "yoursite.com",
  role: "Product designer who builds",
  blurb: "Your one-line bio goes here. 4+ years shipping consumer products end-to-end. Currently working on something interesting.",
  location: "City — City",
  focus: "Focus area · Another focus · Third focus",
  contact: "hi@yoursite.com",
  highlight: { label: "FEATURED PROJECT — LIVE NOW", href: "#" },
  projects: [
    {
      id: "PROJECT_ALPHA.app",
      size: "12.4kb",
      date: "2025-03",
      desc: "Short one-line description of project alpha",
      role: "Solo — design, code",
      status: "LIVE",
      tagline: "Tagline that makes someone want to read more",
      year: "2025",
      platform: "iOS + Web",
      problem: "What problem this solves, in plain language. Two sentences max here. Replace with your own copy.",
      insight: "The key insight that made this work. The thing nobody else noticed.",
      decisions: [
        ["Decision one", "Why it mattered and what it looked like in the product."],
        ["Decision two", "Trade-offs you made and what you learned from them."],
        ["Decision three", "A constraint you embraced rather than fought."],
      ],
    },
    {
      id: "PROJECT_BETA.case",
      size: "38.1kb",
      date: "2025-01",
      desc: "Short one-line description of project beta",
      role: "Product design lead",
      status: "UNRELEASED",
      tagline: "A second tagline",
      year: "2025",
      platform: "iOS — Web",
      problem: "Case study problem statement. Replace this.",
      insight: "Insight goes here.",
      decisions: [
        ["First", "Detail."],
        ["Second", "Detail."],
      ],
    },
    {
      id: "PROJECT_GAMMA.log",
      size: "94.7kb",
      date: "2021-2023",
      desc: "Three products — long-form description",
      role: "founding designer & brand lead",
      status: "ARCHIVED",
      tagline: "Three products, eighteen months",
      year: "2021–2023",
      platform: "Chrome — Web — Mobile",
      problem: "What you were exploring across these products.",
      insight: "What the pivot taught you.",
      decisions: [
        ["Kill the form", "Keep the thesis."],
        ["Speed is a constraint", "Design for fast iteration."],
      ],
    },
    {
      id: "PROJECT_DELTA.dir",
      size: "6.5kb",
      date: "2023-2024",
      desc: "Brand & motion — events and identity",
      role: "Creative director",
      status: "DELIVERED",
      tagline: "Identity, motion, three cities",
      year: "2023–2024",
      platform: "Brand · Motion · Events",
      problem: "Brand brief.",
      insight: "Visual language insight.",
      decisions: [
        ["Identity relaunch", "What changed and why."],
        ["Events", "Three cities, what they shared."],
      ],
    },
  ],
};

window.PORTFOLIO = PORTFOLIO;
